services:
  - type: web
    name: jahul-chatbot-api
    runtime: python
    region: oregon
    branch: main
    plan: free
    rootDir: chatbot-backend
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn app_dynamic:app --bind 0.0.0.0:$PORT
    envVars:
      - key: MONGODB_ATLAS_URI
        value: mongodb+srv://jahulkhan_db_user:cOkS9qN2X7QWTaCE@jahul-chatbot.hqsd1xp.mongodb.net/?retryWrites=true&w=majority
      - key: MONGODB_ATLAS_DB
        value: jahul_chatbot_prod
      - key: ENVIRONMENT
        value: atlas
